POST http://localhost:3050/productos HTTP/1.1
Content-Type: application/json

{
    "nombre":"gorra",
    "precio":"50",
    "unidades":"7",
    "descripción":"gorra de algodon para niños"
}

# {
#     "nombre":"camisa",
#     "precio":"80",
#     "unidades":"30",
#     "descripción":"camisa para mujer y hombre talla unica"
# }

###
GET http://localhost:3050/productos/ HTTP/1.1

###
PUT http://localhost:3050/productos/gorra
Content-Type: application/json

{
    "nombre":"gorra",
    "precio":"50",
    "unidades":"4",
    "descripción":"gorra de algodon para niños"
}

###
PATCH  http://localhost:3050/productos/gorra HTTP/1.1
Content-Type: application/json

{
    "nombre":"gorra",
    "precio":"22",
    "unidades":"4",
    "descripción":"gorra de algodon para niños"
}

###
DELETE http://localhost:3050/productos/gorra HTTP/1.1
